export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "@/styles/globals.scss";
import { JetBrains_Mono } from "next/font/google";

const jetBrains_Mono = JetBrains_Mono({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.className}>{children}</body>
    </html>
  );
}
